name: Rebuild from branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to build from'
        default: 'main'
        required: true
        type: string
        # Uncomment the following to provide a static list of options
        options:
          - main
          - develop
          - staging

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Use the branch provided in the workflow dispatch input
          ref: ${{ github.event.inputs.branch_name }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: '/${Coc}'
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
